### PR TITLE
Use document fragment to reduce intial dom mutations

### PR DESCRIPTION
**Pull request by wilsonpage**

### CODE REVIEW

**Comment by etiennesegonzac** [comment]
Nice!

I know it's not a real-life use case, but can you add a small test calling `render` with a fragment and asserting that it did render inside? Just for peace of mind :)

**Comment by etiennesegonzac** [comment]
Ping @wilsonpage , this is totally ready to land with the small test added :)

**Comment by wilsonpage** [comment]
Sorry got distracted with fixing my profiling setup. I'll get on this asap.

**Comment by wilsonpage** [comment]
Added test. Clear runway for landing ... :airplane:

**Pull request merged**
