### PR TITLE
Guard against moved 0 scroll events (fixes #67)

### LINKED ISSUE #67: `.populateItemDetail()` being called too often
I noticed that we're sometimes getting scroll events that report having moved `0` pixels since the previous event, even when scrolling quite fast. In this case we're setting `geo.idle = true` which means that `.populateItemDetail()` is running.

This causes checkerboarding as we can't render the images fast enough.

### PR DESCRIPTION
**Pull request by wilsonpage**

### CODE REVIEW

**Comment by wilsonpage** [comment]
@etiennesegonzac f?

**Comment by etiennesegonzac** [comment]
Since I had it at some point but removed it, I'd like to cover it with the test :)
I'm thinking something like that (adding context):

``` js
        suite('then slowing down >', function() {
          setup(function() {
            container.scrollTop += 239; // 1/2 viewport
            scheduler.attachDirect.yield();
          });

          test('it catches up but is still skipping details', function() {
            assertCurrentlyRenderedWindow({
              container: container,
              source: source,
              from: 45,
              to: 66,
              expectsNoDetail: true
            });
          });

          test('even during an odd scroll event with no delta', function() {
            container.scrollTop += 0;
            scheduler.attachDirect.yield();

            assertCurrentlyRenderedWindow({
              container: container,
              source: source,
              from: 45,
              to: 66,
              expectsNoDetail: true
            });
          });
[...]
```

**Comment by wilsonpage** [comment]
Why did you choose to remove it?

**Comment by wilsonpage** [comment]
I'm still confused how we're supposed to know what the `from` and `to` values should be?

**Comment by etiennesegonzac** [comment]
wasn't sure it could happen

**Comment by etiennesegonzac** [comment]
the from and to are the same than the parent suite.
showing that we didn't update the rendering.
extracting them to variables might help with readability

**Pull request merged**
