### PR TITLE
Enable gaia-fast-list consumer to set a "rough estimate" of a total l…

### LINKED ISSUE #35: Support "chunked list with cached height"
One of the main gaia use case is probably going to be the following:
- we eventually fetch all the data
- we chunk the fetch and call `reloadData()` for every chunk
- we want to cache and return a complete `fullHeight` to let the user scroll at any point in the list from the get go

We should make this a very happy path :)

### PR DESCRIPTION
**Pull request by etiennesegonzac**
…ist size for a nicer cold launch experience.

(Fixes #35 )

### CODE REVIEW

**Comment by etiennesegonzac** [comment]
The idea is to easily "inject" a cached height with the attribute then remove it once you're done fetching your last chunk.

r? @wilsonpage

**Comment by wilsonpage** [comment]
- Why are we using `height` and not `length`? Perhaps due to section headers? Sounds like we're asking our users to do some nitty gritty work externally in order to get this figure. They must know the height of the gaia-fast-list items and section headers (which could change) and they need to take cache of an appropriate caching strategy to store the number of items and sections.
- Would it make sense for this optmization to be done internally by caching the last known number of items?
- Is it suggested to remove the attribute in-case the list length changes from the initially defined `height`?

**Comment by etiennesegonzac** [comment]
>    Why are we using height and not length? Perhaps due to section headers? Sounds like we're asking our users to do some nitty gritty work externally in order to get this figure. They must know the height of the gaia-fast-list items and section headers (which could change) and they need to take cache of an appropriate caching strategy to store the number of items and sections.

The goal is to enable the user to scroll freely right away, the the full height is what gives us that. It's also a nice single attribute to set for the app (as opposed to numer of items + number of sections + sizes).

>    Would it make sense for this optmization to be done internally by caching the last known number of items?

What I liked about the external attribute is that it could be stored in a render cache _or_ in a cookie _or_ in localstorage etc.. Or in an indexedDB in a worker.

>    Is it suggested to remove the attribute in-case the list length changes from the initially defined height?

Yes. But I'd love suggestions to make it cleaner/more explicit :)

**Comment by etiennesegonzac** [comment]
One use case I have in mind is: `import.html` in the contacts app imports 2000 contacts, set's an approximate cache height to the `sessionStorage`.
Then we load `list.html` but we can set the height right away so that the list is fully scrollable while we "chunk fetch" the content.

**Comment by etiennesegonzac** [comment]
The conclusion I'm slowly reaching is that maybe the internal caching you're working on will be enough (especially if we cache the total height too).
But if we complement it with a lightweight cache for the height it should be external in order to enable those use cases where the code handling new content is in a totally different context.

**Comment by etiennesegonzac** [comment]
new version @wilsonpage !

**Comment by etiennesegonzac** [comment]
Fixes issue #49

**Comment by wilsonpage** [comment]
Nice simple patch, let's land it!

**Pull request merged**
