### PR TITLE
Added a public 'rendered' promise to define when content has been drawn (used by gaia-fast-list)

### PR DESCRIPTION
**Pull request by wilsonpage**

### CODE REVIEW

**Comment by wilsonpage** [comment]
@etiennesegonzac r?

**Comment by etiennesegonzac** [comment]
Since the patch is still small enough can you
- add a simple test
- use it to trigger .layerize 
  ? :)

**Comment by wilsonpage** [comment]
Added simple test. Have changed `.layerize()` call in new gaia-components/gaia-fast-list repo.

**Comment by wilsonpage** [comment]
@etiennesegonzac r?

**Pull request merged**
