### PR TITLE
Separate examples from source code

### PR DESCRIPTION
**Pull request by wilsonpage**

### CODE REVIEW

**Comment by etiennesegonzac** [comment]
We need to update the `package.json` so that the linter still run against `scheduled-list.js` (currently it targeted `lib/*.js`)

**Comment by etiennesegonzac** [comment]
For the example to be installable with the WebIDE we need to make symlinks for `bower_components` and `scheduled-list.js` (instead of `../../` includes)

**Comment by etiennesegonzac** [comment]
Oh and we also need to update the `bower.json` "main" field.

**Comment by wilsonpage** [comment]
Moved `bower_components` into `examples/` and symlinked `scheduled-list.js`

**Comment by etiennesegonzac** [comment]
Cool, a lot cleaner :)

**Pull request merged**
